"""
build_exe.py
============
Automated build script for Voicer Studio.
Compiles the native Windows executable (VoicerStudio.exe) with embedded icons,
version metadata from config.py, and zero-console configuration.

Usage:
    python build_exe.py
"""

import sys
import os
import shutil
import subprocess
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent

# ── Load config ───────────────────────────────────────────────────────────────
try:
    from config import APP_NAME, APP_VERSION
except ImportError:
    APP_NAME = "The Choice Voicer Dialogue Extractor"
    APP_VERSION = "1.1.0"

def log(msg: str, status: str = "INFO"):
    icons = {"INFO": "[-]", "OK": "[+]", "WARN": "[!]", "ERR": "[x]"}
    print(f"{icons.get(status, '[-]')} {msg}")

def find_tool(name: str) -> str | None:
    path = shutil.which(name)
    if path:
        return path
    # Common MSYS2 paths
    msys_paths = [
        Path("C:/msys64/ucrt64/bin") / f"{name}.exe",
        Path("C:/msys64/mingw64/bin") / f"{name}.exe",
        Path("C:/MinGW/bin") / f"{name}.exe",
    ]
    for p in msys_paths:
        if p.exists():
            return str(p)
    return None

def step_generate_icons():
    log("Checking application icons...", "INFO")
    ico_path = ROOT_DIR / "assets" / "app_icon.ico"
    png_path = ROOT_DIR / "assets" / "app_icon.png"

    if not ico_path.exists() or not png_path.exists():
        log("Generating studio app icons (assets/app_icon.ico & .png)...", "INFO")
        from assets.generate_icon import generate_icons
        generate_icons(ROOT_DIR / "assets")
        log("Icons generated successfully.", "OK")
    else:
        log(f"Icons verified: {ico_path.name}", "OK")

def step_generate_resource_file():
    log(f"Generating launcher.rc for version {APP_VERSION}...", "INFO")
    # Parse version into 4 parts: major, minor, patch, build
    v_parts = APP_VERSION.split(".")
    while len(v_parts) < 4:
        v_parts.append("0")
    v_comma = ",".join(v_parts[:4])
    v_dotted = ".".join(v_parts[:4])

    rc_content = f"""// launcher.rc — Generated by build_exe.py
#include <windows.h>

1 ICON "assets/app_icon.ico"

1 VERSIONINFO
FILEVERSION     {v_comma}
PRODUCTVERSION  {v_comma}
FILEFLAGSMASK   VS_FFI_FILEFLAGSMASK
FILEFLAGS       0
FILEOS          VOS_NT_WINDOWS32
FILETYPE        VFT_APP
FILESUBTYPE     VFT2_UNKNOWN
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName",      "The Choice Voicer"
            VALUE "FileDescription",  "Voicer Studio — Dialogue Extractor & Audio Engine"
            VALUE "FileVersion",      "{v_dotted}"
            VALUE "InternalName",     "VoicerStudio"
            VALUE "LegalCopyright",   "Copyright (c) 2026 The Choice Voicer"
            VALUE "OriginalFilename", "VoicerStudio.exe"
            VALUE "ProductName",      "Voicer Studio"
            VALUE "ProductVersion",   "{v_dotted}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1200
    END
END
"""
    rc_file = ROOT_DIR / "launcher.rc"
    rc_file.write_text(rc_content, encoding="utf-8")
    log("Resource file launcher.rc updated.", "OK")

def step_compile():
    gcc = find_tool("gcc")
    windres = find_tool("windres")

    if not gcc or not windres:
        log("GCC or Windres compiler not found in PATH or MSYS2.", "ERR")
        log("Please install MSYS2 or MinGW to compile VoicerStudio.exe.", "WARN")
        return False

    log(f"Using compiler: {gcc}", "INFO")
    log(f"Using resource compiler: {windres}", "INFO")

    # Step 1: Compile .rc -> .res
    log("Compiling Windows resources (launcher.res)...", "INFO")
    cmd_rc = [windres, "launcher.rc", "-O", "coff", "-o", "launcher.res"]
    res_rc = subprocess.run(cmd_rc, cwd=str(ROOT_DIR), capture_output=True, text=True)
    if res_rc.returncode != 0:
        log(f"windres failed: {res_rc.stderr}", "ERR")
        return False

    # Step 2: Compile launcher.c + launcher.res -> VoicerStudio.exe
    target_exe = ROOT_DIR / "VoicerStudio.exe"
    log(f"Compiling standalone GUI executable ({target_exe.name})...", "INFO")
    cmd_gcc = [
        gcc,
        "-O2",
        "-mwindows",
        "-municode",
        "-s",
        "launcher.c",
        "launcher.res",
        "-o",
        str(target_exe.name)
    ]
    res_gcc = subprocess.run(cmd_gcc, cwd=str(ROOT_DIR), capture_output=True, text=True)
    if res_gcc.returncode != 0:
        log(f"gcc failed: {res_gcc.stderr}", "ERR")
        return False

    # Clean up intermediate object
    res_file = ROOT_DIR / "launcher.res"
    if res_file.exists():
        try:
            res_file.unlink()
        except Exception:
            pass

    size_kb = target_exe.stat().st_size / 1024.0
    log(f"Successfully compiled {target_exe.name} ({size_kb:.1f} KB)!", "OK")
    return True

def main():
    print("=" * 60)
    print(f"  VOICER STUDIO — EXECUTABLE BUILDER v{APP_VERSION}")
    print("=" * 60)

    try:
        step_generate_icons()
        step_generate_resource_file()
        ok = step_compile()

        if ok:
            print("\n" + "=" * 60)
            print("  BUILD SUCCESSFUL!")
            print("  Output: VoicerStudio.exe")
            print("  - True Windows GUI application (no CMD console window)")
            print("  - Auto environment check & single-click launcher")
            print("  - Embedded icon & version metadata")
            print("=" * 60 + "\n")
            return 0
        else:
            print("\n[!] Build failed. Check errors above.")
            return 1
    except Exception as e:
        log(f"Unexpected error during build: {e}", "ERR")
        return 1

if __name__ == "__main__":
    sys.exit(main())
