"""
scripts/build_exe.py
====================
Compiles the native Windows launcher (VoicerStudio.exe) with embedded icons,
version metadata, and zero-console window subsystem.
"""

import sys
import os
import shutil
import subprocess
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPTS_DIR.parent
sys.path.insert(0, str(ROOT_DIR))

try:
    from config import APP_NAME, APP_VERSION
except ImportError:
    APP_NAME = "Voicer Studio"
    APP_VERSION = "1.1.0"

def log(msg: str, status: str = "INFO"):
    icons = {"INFO": "[-]", "OK": "[+]", "WARN": "[!]", "ERR": "[x]"}
    print(f"{icons.get(status, '[-]')} {msg}")

def find_tool(name: str) -> str | None:
    path = shutil.which(name)
    if path:
        return path
    msys_paths = [
        Path("C:/msys64/ucrt64/bin") / f"{name}.exe",
        Path("C:/msys64/mingw64/bin") / f"{name}.exe",
        Path("C:/MinGW/bin") / f"{name}.exe",
    ]
    for p in msys_paths:
        if p.exists():
            return str(p)
    return None

def step_generate_resource_file():
    log(f"Generating launcher.rc for version {APP_VERSION}...", "INFO")
    v_parts = APP_VERSION.split(".")
    while len(v_parts) < 4:
        v_parts.append("0")
    v_comma = ",".join(v_parts[:4])
    v_dotted = ".".join(v_parts[:4])

    ico_path = (ROOT_DIR / "assets" / "app_icon.ico").resolve().as_posix()

    rc_content = f"""// launcher.rc — Generated by build_exe.py
#include <windows.h>

1 ICON "{ico_path}"

1 VERSIONINFO
FILEVERSION     {v_comma}
PRODUCTVERSION  {v_comma}
FILEFLAGSMASK   VS_FFI_FILEFLAGSMASK
FILEFLAGS       0
FILEOS          VOS_NT_WINDOWS32
FILETYPE        VFT_APP
FILESUBTYPE     VFT2_UNKNOWN
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName",      "The Choice Voicer"
            VALUE "FileDescription",  "Voicer Studio — Dialogue Extractor & Audio Separation Suite"
            VALUE "FileVersion",      "{v_dotted}"
            VALUE "InternalName",     "VoicerStudio"
            VALUE "LegalCopyright",   "Copyright (c) 2026 The Choice Voicer"
            VALUE "OriginalFilename", "VoicerStudio.exe"
            VALUE "ProductName",      "Voicer Studio"
            VALUE "ProductVersion",   "{v_dotted}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1200
    END
END
"""
    rc_file = SCRIPTS_DIR / "launcher.rc"
    rc_file.write_text(rc_content, encoding="utf-8")
    log("Resource file launcher.rc updated.", "OK")
    return rc_file

def step_compile():
    gcc = find_tool("gcc")
    windres = find_tool("windres")

    if not gcc or not windres:
        log("GCC or Windres compiler not found.", "ERR")
        return False

    log(f"Using compiler: {gcc}", "INFO")
    log(f"Using resource compiler: {windres}", "INFO")

    rc_file = step_generate_resource_file()
    res_file = SCRIPTS_DIR / "launcher.res"
    launcher_c = SCRIPTS_DIR / "launcher.c"
    target_exe = ROOT_DIR / "VoicerStudio.exe"

    # Step 1: Compile .rc -> .res
    log("Compiling Windows resources...", "INFO")
    cmd_rc = [windres, str(rc_file), "-O", "coff", "-o", str(res_file)]
    res_rc = subprocess.run(cmd_rc, cwd=str(SCRIPTS_DIR), capture_output=True, text=True)
    if res_rc.returncode != 0:
        log(f"windres failed: {res_rc.stderr}", "ERR")
        return False

    # Step 2: Compile launcher.c + launcher.res -> VoicerStudio.exe
    log(f"Compiling standalone GUI executable ({target_exe.name})...", "INFO")
    if target_exe.exists():
        try:
            with open(target_exe, "r+b"):
                pass
        except PermissionError:
            log(f"{target_exe.name} is currently running! Attempting to close running process...", "WARN")
            subprocess.run(["taskkill", "/F", "/IM", target_exe.name], capture_output=True)
            import time
            time.sleep(0.8)

    cmd_gcc = [
        gcc,
        "-O2",
        "-mwindows",
        "-municode",
        "-s",
        str(launcher_c),
        str(res_file),
        "-o",
        str(target_exe)
    ]
    res_gcc = subprocess.run(cmd_gcc, cwd=str(ROOT_DIR), capture_output=True, text=True)
    if res_gcc.returncode != 0:
        log(f"gcc failed: {res_gcc.stderr}", "ERR")
        return False

    # Clean up intermediate object
    if res_file.exists():
        try:
            res_file.unlink()
        except Exception:
            pass

    size_kb = target_exe.stat().st_size / 1024.0
    log(f"Successfully compiled {target_exe.name} ({size_kb:.1f} KB) at {target_exe}!", "OK")
    return True

if __name__ == "__main__":
    success = step_compile()
    sys.exit(0 if success else 1)
